ALTER TABLE metrics ADD COLUMN unit TEXT;
ALTER TABLE metrics ADD COLUMN count REAL;
ALTER TABLE metrics ADD COLUMN sum REAL;
ALTER TABLE metrics ADD COLUMN min REAL;
ALTER TABLE metrics ADD COLUMN max REAL;
ALTER TABLE metrics ADD COLUMN buckets TEXT;
ALTER TABLE metrics ADD COLUMN quantiles TEXT;
